export const GET_POSITIONS = "GMAP_GET_POSITIONS";
export const GET_POSITIONS_SUCCESS = "GMAP_GET_POSITIONS";
export const GET_POSITIONS_ERROR = "GMAP_GET_POSITIONS";

export const POLL_POSITIONS = "GMAP_POLL_POSITIONS";

export const LEFT_SET_TIME = "LEFT_SET_TIME"
