export const GET_POSITIONS = "GMAP_GET_POSITIONS";
export const GET_POSITIONS_SUCCESS = "GMAP_GET_POSITIONS_SUCCESS";
export const GET_POSITIONS_ERROR = "GMAP_GET_POSITIONS_ERROR";

export const POLL_POSITIONS = "GMAP_POLL_POSITIONS";

export const LEFT_SET_TIME = "LEFT_SET_TIME"

export const GET_POSITIONS_HOUR = "GMAP_GET_POSITIONS_HOUR";
export const GET_POSITIONS_HOUR_SUCCESS = "GMAP_GET_POSITIONS_HOUR_SUCCESS";
export const GET_POSITIONS_HOUR_ERROR = "GMAP_GET_POSITIONS_HOUR_ERROR";

export const SET_SLIDER_VALUE = "SET_SLIDER_VALUE";
export const SET_SLIDER_VALUE_SUCCESS = "SET_SLIDER_VALUE_SUCCESS";
export const SET_SLIDER_VALUE_ERROR = "SET_SLIDER_VALUE_ERROR";

export const SET_SLIDER_VALUE_ONCE = "SET_SLIDER_VALUE_ONCE";
export const SET_SLIDER_VALUE_ONCE_SUCCESS = "SET_SLIDER_VALUE_ONCE_SUCCESS";
export const SET_SLIDER_VALUE_ONCE_ERROR = "SET_SLIDER_VALUE_ONCE_ERROR";

export const START_LOOP = "START_LOOP";
export const START_LOOP_SUCCESS = "START_LOOP_SUCCESS";
export const START_LOOP_ERROR = "START_LOOP_ERROR";
